# Generated by Django 3.2.4 on 2021-07-12 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 12, 6, 6, 33, 188149)),
        ),
    ]
