# Generated by Django 3.2.4 on 2021-07-12 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 12, 6, 14, 4, 184697)),
        ),
    ]
