# Generated by Django 3.2.4 on 2021-07-26 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210712_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 10, 47, 19, 800264)),
        ),
    ]
