# Generated by Django 3.2.4 on 2021-07-26 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Hight',
            new_name='Height',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 26, 13, 5, 37, 952619)),
        ),
    ]
